#!/system/bin/sh
#
#   Copyright 2013 Project SuperiorIrkenOrgans
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

SYS_VM=/proc/sys/vm/dirty

if [ -e /proc/sys/vm ]; then

	sysctl -w kernel.randomize_va_space=0 \
		kernel.random.write_wakeup_threshold=128 \
		kernel.random.read_wakeup_threshold=1366
	
	echo 1000 > $SYS_VM\_expire_centisecs
	echo 500 > $SYS_VM\_writeback_centisecs

	# Check for the presents fo rngd-tool binary
	
	if [ -e /system/bin/rngd ]; then
		rngd
	else
		if [ -e /system/xbin/rngd ]; then
			rngd
		else
			echo "No rngd-tool binary, skipping entropy generator!"
			exit 1
		fi
	fi
else
	echo "Unable to apply kernel changes!"
	exit 1
fi

